version: '3'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - SERVICES=lambda,cloudwatch
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=dataworks-ingestion-metadata-interface_default
      - ENVIRONMENT=local
      - APPLICATION=ingestion-metadata-provisioner
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  metadatastore:
    image: mysql:5.7
    restart: always
    container_name: metadatastore
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "metadatastore"


  integration-tests:
    image: integration-tests:latest
    container_name: integration-tests
    build:
      dockerfile: images/Dockerfile
      context: .
    depends_on:
      - metadatastore
      - localstack


